// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO catalog_categories (id, tenant_id, name, sort_order, sold_out)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, sort_order, sold_out, created_at, updated_at
`

type CreateCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	SoldOut   bool        `json:"sold_out"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.SortOrder,
		arg.SoldOut,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.SoldOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO catalog_items (
    id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight, created_at, updated_at
`

type CreateItemParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Name         string      `json:"name"`
	PriceCents   int64       `json:"price_cents"`
	SortOrder    int32       `json:"sort_order"`
	SoldOut      bool        `json:"sold_out"`
	SoldByWeight bool        `json:"sold_by_weight"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CatalogItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.PriceCents,
		arg.SortOrder,
		arg.SoldOut,
		arg.SoldByWeight,
	)
	var i CatalogItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.PriceCents,
		&i.SortOrder,
		&i.SoldOut,
		&i.SoldByWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, tenant_id, name, sort_order, sold_out, created_at, updated_at
FROM catalog_categories
WHERE tenant_id = $1 AND id = $2
`

type GetCategoryParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.TenantID, arg.ID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.SoldOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight, created_at, updated_at
FROM catalog_items
WHERE tenant_id = $1 AND id = $2
`

type GetItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (CatalogItem, error) {
	row := q.db.QueryRow(ctx, getItem, arg.TenantID, arg.ID)
	var i CatalogItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.PriceCents,
		&i.SortOrder,
		&i.SoldOut,
		&i.SoldByWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, sort_order, sold_out, created_at, updated_at
FROM catalog_categories
WHERE tenant_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListCategories(ctx context.Context, tenantID pgtype.UUID) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogCategory{}
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.SoldOut,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight, created_at, updated_at
FROM catalog_items
WHERE tenant_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListItems(ctx context.Context, tenantID pgtype.UUID) ([]CatalogItem, error) {
	rows, err := q.db.Query(ctx, listItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogItem{}
	for rows.Next() {
		var i CatalogItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.PriceCents,
			&i.SortOrder,
			&i.SoldOut,
			&i.SoldByWeight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategory = `-- name: ListItemsByCategory :many
SELECT id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight, created_at, updated_at
FROM catalog_items
WHERE tenant_id = $1 AND category_id = $2
ORDER BY sort_order, id
`

type ListItemsByCategoryParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]CatalogItem, error) {
	rows, err := q.db.Query(ctx, listItemsByCategory, arg.TenantID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogItem{}
	for rows.Next() {
		var i CatalogItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.PriceCents,
			&i.SortOrder,
			&i.SoldOut,
			&i.SoldByWeight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategorySoldOut = `-- name: SetCategorySoldOut :one
UPDATE catalog_categories
SET sold_out = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, name, sort_order, sold_out, created_at, updated_at
`

type SetCategorySoldOutParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	SoldOut  bool        `json:"sold_out"`
}

func (q *Queries) SetCategorySoldOut(ctx context.Context, arg SetCategorySoldOutParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, setCategorySoldOut, arg.TenantID, arg.ID, arg.SoldOut)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.SoldOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setItemSoldOut = `-- name: SetItemSoldOut :one
UPDATE catalog_items
SET sold_out = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, category_id, name, price_cents, sort_order, sold_out, sold_by_weight, created_at, updated_at
`

type SetItemSoldOutParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	SoldOut  bool        `json:"sold_out"`
}

func (q *Queries) SetItemSoldOut(ctx context.Context, arg SetItemSoldOutParams) (CatalogItem, error) {
	row := q.db.QueryRow(ctx, setItemSoldOut, arg.TenantID, arg.ID, arg.SoldOut)
	var i CatalogItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.PriceCents,
		&i.SortOrder,
		&i.SoldOut,
		&i.SoldByWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
