// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (tenant_id, id, name, phone, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING tenant_id, id, name, phone, email, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Phone    string      `json:"phone"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerAddress = `-- name: CreateCustomerAddress :one
INSERT INTO customer_addresses (
    tenant_id, id, customer_id, label, street, number,
    complement, neighborhood, city, state, postal_code, reference
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING tenant_id, id, customer_id, label, street, number, complement, neighborhood, city, state, postal_code, reference, created_at, updated_at
`

type CreateCustomerAddressParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ID           pgtype.UUID `json:"id"`
	CustomerID   pgtype.UUID `json:"customer_id"`
	Label        pgtype.Text `json:"label"`
	Street       string      `json:"street"`
	Number       string      `json:"number"`
	Complement   pgtype.Text `json:"complement"`
	Neighborhood string      `json:"neighborhood"`
	City         string      `json:"city"`
	State        string      `json:"state"`
	PostalCode   string      `json:"postal_code"`
	Reference    pgtype.Text `json:"reference"`
}

func (q *Queries) CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CustomerAddress, error) {
	row := q.db.QueryRow(ctx, createCustomerAddress,
		arg.TenantID,
		arg.ID,
		arg.CustomerID,
		arg.Label,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Reference,
	)
	var i CustomerAddress
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.CustomerID,
		&i.Label,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT tenant_id, id, name, phone, email, created_at, updated_at FROM customers
WHERE tenant_id = $1 AND id = $2
`

type GetCustomerParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.TenantID, arg.ID)
	var i Customer
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerAddress = `-- name: GetCustomerAddress :one
SELECT tenant_id, id, customer_id, label, street, number, complement, neighborhood, city, state, postal_code, reference, created_at, updated_at FROM customer_addresses
WHERE tenant_id = $1 AND id = $2
`

type GetCustomerAddressParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetCustomerAddress(ctx context.Context, arg GetCustomerAddressParams) (CustomerAddress, error) {
	row := q.db.QueryRow(ctx, getCustomerAddress, arg.TenantID, arg.ID)
	var i CustomerAddress
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.CustomerID,
		&i.Label,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerAddresses = `-- name: ListCustomerAddresses :many
SELECT tenant_id, id, customer_id, label, street, number, complement, neighborhood, city, state, postal_code, reference, created_at, updated_at FROM customer_addresses
WHERE tenant_id = $1 AND customer_id = $2
ORDER BY id
`

type ListCustomerAddressesParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

func (q *Queries) ListCustomerAddresses(ctx context.Context, arg ListCustomerAddressesParams) ([]CustomerAddress, error) {
	rows, err := q.db.Query(ctx, listCustomerAddresses, arg.TenantID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerAddress{}
	for rows.Next() {
		var i CustomerAddress
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.CustomerID,
			&i.Label,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.Neighborhood,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT tenant_id, id, name, phone, email, created_at, updated_at FROM customers
WHERE tenant_id = $1
ORDER BY name, id
`

func (q *Queries) ListCustomers(ctx context.Context, tenantID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
