// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_users (
    id, name, cpf, email, phone, image_url, password_hash
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, cpf, email, phone, image_url, password_hash, created_at, updated_at
`

type CreateAppUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Cpf          string      `json:"cpf"`
	Email        string      `json:"email"`
	Phone        string      `json:"phone"`
	ImageUrl     pgtype.Text `json:"image_url"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.ID,
		arg.Name,
		arg.Cpf,
		arg.Email,
		arg.Phone,
		arg.ImageUrl,
		arg.PasswordHash,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.ImageUrl,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id, user_id, active_tenant_id, token_hash, expires_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, active_tenant_id, token_hash, expires_at, revoked_at, created_at
`

type CreateAuthSessionParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ActiveTenantID pgtype.UUID        `json:"active_tenant_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.ActiveTenantID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveTenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantMembership = `-- name: CreateTenantMembership :one
INSERT INTO tenant_memberships (
    tenant_id, user_id, title, status, permissions
)
VALUES ($1, $2, $3, $4, $5)
RETURNING tenant_id, user_id, title, status, permissions, created_at, updated_at
`

type CreateTenantMembershipParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Status      string      `json:"status"`
	Permissions []string    `json:"permissions"`
}

func (q *Queries) CreateTenantMembership(ctx context.Context, arg CreateTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, createTenantMembership,
		arg.TenantID,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.Permissions,
	)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppUserByEmail = `-- name: GetAppUserByEmail :one
SELECT id, name, cpf, email, phone, image_url, password_hash, created_at, updated_at
FROM app_users
WHERE lower(email) = lower($1)
LIMIT 1
`

func (q *Queries) GetAppUserByEmail(ctx context.Context, lower string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByEmail, lower)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.ImageUrl,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppUserByID = `-- name: GetAppUserByID :one
SELECT id, name, cpf, email, phone, image_url, password_hash, created_at, updated_at
FROM app_users
WHERE id = $1
`

func (q *Queries) GetAppUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.ImageUrl,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByTokenHash = `-- name: GetAuthSessionByTokenHash :one
SELECT id, user_id, active_tenant_id, token_hash, expires_at, revoked_at, created_at
FROM auth_sessions
WHERE token_hash = $1
`

func (q *Queries) GetAuthSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveTenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMembership = `-- name: GetTenantMembership :one
SELECT tenant_id, user_id, title, status, permissions, created_at, updated_at
FROM tenant_memberships
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTenantMembership(ctx context.Context, arg GetTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, getTenantMembership, arg.TenantID, arg.UserID)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollaborators = `-- name: ListCollaborators :many
SELECT
    u.id, u.name, u.cpf, u.email, u.phone, u.image_url, u.password_hash,
    m.tenant_id, m.title, m.status, m.permissions
FROM tenant_memberships m
JOIN app_users u ON u.id = m.user_id
WHERE m.tenant_id = $1
  AND (
    $2::text = '' OR
    lower(u.name) LIKE '%' || lower($2::text) || '%' OR
    lower(u.email) LIKE '%' || lower($2::text) || '%' OR
    lower(u.phone) LIKE '%' || lower($2::text) || '%' OR
    lower(m.title) LIKE '%' || lower($2::text) || '%'
  )
ORDER BY u.name, u.id
`

type ListCollaboratorsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Search   string      `json:"search"`
}

type ListCollaboratorsRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Cpf          string      `json:"cpf"`
	Email        string      `json:"email"`
	Phone        string      `json:"phone"`
	ImageUrl     pgtype.Text `json:"image_url"`
	PasswordHash string      `json:"password_hash"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Title        string      `json:"title"`
	Status       string      `json:"status"`
	Permissions  []string    `json:"permissions"`
}

func (q *Queries) ListCollaborators(ctx context.Context, arg ListCollaboratorsParams) ([]ListCollaboratorsRow, error) {
	rows, err := q.db.Query(ctx, listCollaborators, arg.TenantID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollaboratorsRow{}
	for rows.Next() {
		var i ListCollaboratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cpf,
			&i.Email,
			&i.Phone,
			&i.ImageUrl,
			&i.PasswordHash,
			&i.TenantID,
			&i.Title,
			&i.Status,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :one
UPDATE auth_sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, active_tenant_id, token_hash, expires_at, revoked_at, created_at
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id pgtype.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, revokeAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveTenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setTenantMembershipStatus = `-- name: SetTenantMembershipStatus :one
UPDATE tenant_memberships
SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND user_id = $2
RETURNING tenant_id, user_id, title, status, permissions, created_at, updated_at
`

type SetTenantMembershipStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Status   string      `json:"status"`
}

func (q *Queries) SetTenantMembershipStatus(ctx context.Context, arg SetTenantMembershipStatusParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, setTenantMembershipStatus, arg.TenantID, arg.UserID, arg.Status)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
