// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Cpf          string             `json:"cpf"`
	Email        string             `json:"email"`
	Phone        string             `json:"phone"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ActiveTenantID pgtype.UUID        `json:"active_tenant_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CatalogCategory struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	SoldOut   bool               `json:"sold_out"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CatalogItem struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Name         string             `json:"name"`
	PriceCents   int64              `json:"price_cents"`
	SortOrder    int32              `json:"sort_order"`
	SoldOut      bool               `json:"sold_out"`
	SoldByWeight bool               `json:"sold_by_weight"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CustomerAddress struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Label        pgtype.Text        `json:"label"`
	Street       string             `json:"street"`
	Number       string             `json:"number"`
	Complement   pgtype.Text        `json:"complement"`
	Neighborhood string             `json:"neighborhood"`
	City         string             `json:"city"`
	State        string             `json:"state"`
	PostalCode   string             `json:"postal_code"`
	Reference    pgtype.Text        `json:"reference"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Establishment struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Source                string             `json:"source"`
	Status                string             `json:"status"`
	TotalCents            int64              `json:"total_cents"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
	CustomerNameSnapshot  pgtype.Text        `json:"customer_name_snapshot"`
	CustomerPhoneSnapshot pgtype.Text        `json:"customer_phone_snapshot"`
	CustomerEmailSnapshot pgtype.Text        `json:"customer_email_snapshot"`
	AddressID             pgtype.UUID        `json:"address_id"`
	AddressSnapshot       []byte             `json:"address_snapshot"`
	FulfillmentType       string             `json:"fulfillment_type"`
	ScheduledAt           pgtype.Timestamptz `json:"scheduled_at"`
	Notes                 string             `json:"notes"`
}

type OrderIdempotency struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	OrderID            pgtype.UUID        `json:"order_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrderID        pgtype.UUID `json:"order_id"`
	LineNo         int32       `json:"line_no"`
	ItemID         pgtype.UUID `json:"item_id"`
	NameSnapshot   string      `json:"name_snapshot"`
	Quantity       int64       `json:"quantity"`
	UnitPriceCents int64       `json:"unit_price_cents"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TenantMembership struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Permissions []string           `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
