// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, tenant_id, source, status, total_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, source, status, total_cents, created_at, updated_at
`

type CreateOrderParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Source     string      `json:"source"`
	Status     string      `json:"status"`
	TotalCents int64       `json:"total_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.TenantID,
		arg.Source,
		arg.Status,
		arg.TotalCents,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderIdempotency = `-- name: CreateOrderIdempotency :one
INSERT INTO order_idempotency (
    tenant_id, idempotency_key, request_fingerprint, order_id
)
VALUES ($1, $2, $3, $4)
RETURNING tenant_id, idempotency_key, request_fingerprint, order_id, created_at
`

type CreateOrderIdempotencyParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	IdempotencyKey     string      `json:"idempotency_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
	OrderID            pgtype.UUID `json:"order_id"`
}

func (q *Queries) CreateOrderIdempotency(ctx context.Context, arg CreateOrderIdempotencyParams) (OrderIdempotency, error) {
	row := q.db.QueryRow(ctx, createOrderIdempotency,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.OrderID,
	)
	var i OrderIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    tenant_id, order_id, line_no, item_id, name_snapshot, quantity, unit_price_cents
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING tenant_id, order_id, line_no, item_id, name_snapshot, quantity, unit_price_cents
`

type CreateOrderItemParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrderID        pgtype.UUID `json:"order_id"`
	LineNo         int32       `json:"line_no"`
	ItemID         pgtype.UUID `json:"item_id"`
	NameSnapshot   string      `json:"name_snapshot"`
	Quantity       int64       `json:"quantity"`
	UnitPriceCents int64       `json:"unit_price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.TenantID,
		arg.OrderID,
		arg.LineNo,
		arg.ItemID,
		arg.NameSnapshot,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.TenantID,
		&i.OrderID,
		&i.LineNo,
		&i.ItemID,
		&i.NameSnapshot,
		&i.Quantity,
		&i.UnitPriceCents,
	)
	return i, err
}

const deleteOrderIdempotency = `-- name: DeleteOrderIdempotency :exec
DELETE FROM order_idempotency
WHERE tenant_id = $1 AND idempotency_key = $2
`

type DeleteOrderIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) DeleteOrderIdempotency(ctx context.Context, arg DeleteOrderIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteOrderIdempotency, arg.TenantID, arg.IdempotencyKey)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, tenant_id, source, status, total_cents, created_at, updated_at
FROM orders
WHERE tenant_id = $1 AND id = $2
`

type GetOrderParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.TenantID, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderIdempotency = `-- name: GetOrderIdempotency :one
SELECT tenant_id, idempotency_key, request_fingerprint, order_id, created_at
FROM order_idempotency
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetOrderIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetOrderIdempotency(ctx context.Context, arg GetOrderIdempotencyParams) (OrderIdempotency, error) {
	row := q.db.QueryRow(ctx, getOrderIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i OrderIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT tenant_id, order_id, line_no, item_id, name_snapshot, quantity, unit_price_cents
FROM order_items
WHERE tenant_id = $1 AND order_id = $2
ORDER BY line_no
`

type ListOrderItemsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrderID  pgtype.UUID `json:"order_id"`
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.TenantID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.TenantID,
			&i.OrderID,
			&i.LineNo,
			&i.ItemID,
			&i.NameSnapshot,
			&i.Quantity,
			&i.UnitPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, tenant_id, source, status, total_cents, created_at, updated_at
FROM orders
WHERE tenant_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListOrders(ctx context.Context, tenantID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.Status,
			&i.TotalCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderForUpdate = `-- name: LockOrderForUpdate :one
SELECT id, tenant_id, source, status, total_cents, created_at, updated_at
FROM orders
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockOrderForUpdateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockOrderForUpdate(ctx context.Context, arg LockOrderForUpdateParams) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrderForUpdate, arg.TenantID, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, source, status, total_cents, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.TenantID, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Status,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
