// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id, tenant_id, aggregate_type, aggregate_id, event_type, payload
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, aggregate_type, aggregate_id, event_type, payload, occurred_at, published_at, attempts
`

type CreateOutboxEventParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.OccurredAt,
		&i.PublishedAt,
		&i.Attempts,
	)
	return i, err
}

const incrementOutboxEventAttempts = `-- name: IncrementOutboxEventAttempts :exec
UPDATE outbox_events
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOutboxEventAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOutboxEventAttempts, id)
	return err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, tenant_id, aggregate_type, aggregate_id, event_type, payload, occurred_at, published_at, attempts
FROM outbox_events
WHERE published_at IS NULL
ORDER BY occurred_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.PublishedAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
