// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error)
	CreateEstablishment(ctx context.Context, arg CreateEstablishmentParams) (Establishment, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (CatalogItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderIdempotency(ctx context.Context, arg CreateOrderIdempotencyParams) (OrderIdempotency, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteOrderIdempotency(ctx context.Context, arg DeleteOrderIdempotencyParams) error
	GetCategory(ctx context.Context, arg GetCategoryParams) (CatalogCategory, error)
	GetEstablishment(ctx context.Context, arg GetEstablishmentParams) (Establishment, error)
	GetItem(ctx context.Context, arg GetItemParams) (CatalogItem, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetOrderIdempotency(ctx context.Context, arg GetOrderIdempotencyParams) (OrderIdempotency, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	IncrementOutboxEventAttempts(ctx context.Context, id pgtype.UUID) error
	ListCategories(ctx context.Context, tenantID pgtype.UUID) ([]CatalogCategory, error)
	ListItems(ctx context.Context, tenantID pgtype.UUID) ([]CatalogItem, error)
	ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]CatalogItem, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListOrders(ctx context.Context, tenantID pgtype.UUID) ([]Order, error)
	ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	LockOrderForUpdate(ctx context.Context, arg LockOrderForUpdateParams) (Order, error)
	MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error
	SetCategorySoldOut(ctx context.Context, arg SetCategorySoldOutParams) (CatalogCategory, error)
	SetItemSoldOut(ctx context.Context, arg SetItemSoldOutParams) (CatalogItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
