// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEstablishment = `-- name: CreateEstablishment :one
INSERT INTO establishments (id, tenant_id, name, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, timezone, created_at, updated_at
`

type CreateEstablishmentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) CreateEstablishment(ctx context.Context, arg CreateEstablishmentParams) (Establishment, error) {
	row := q.db.QueryRow(ctx, createEstablishment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Timezone,
	)
	var i Establishment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateTenantParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getEstablishment = `-- name: GetEstablishment :one
SELECT id, tenant_id, name, timezone, created_at, updated_at
FROM establishments
WHERE tenant_id = $1 AND id = $2
`

type GetEstablishmentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetEstablishment(ctx context.Context, arg GetEstablishmentParams) (Establishment, error) {
	row := q.db.QueryRow(ctx, getEstablishment, arg.TenantID, arg.ID)
	var i Establishment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
